### ISSUE TITLE
Block settings for number of posts not saving

### ISSUE THREAD

**Issue by onetrev** [WebberZone/contextual-related-posts#167]
I'm using CRP in the WP Site Editor (Full Site Editing). When I try to edit the Number of Posts or Offset, I save the Site Template, and the values are still there but on the front end the number of posts displayed does not change. 

If I refresh the page / navigate away and back to the template I'm editing in the Site Editor (i.e. Single Post template) then the original default values of 6 for Number of Posts and 0 for Offset is back again.

Also, a tiny other issue, so not worth probably creating another bug report, but the long line of text in the "Other Attributes" box creates horizontal scrollbars in the Block Settings area.

![setting-does-not-apply-resets](https://user-images.githubusercontent.com/597601/166218447-1aaf3c16-0e61-4d59-86be-12cd5086db76.jpg)
![text-creates-scrollbar](https://user-images.githubusercontent.com/597601/166218453-74a4ed7f-a476-4310-96d2-3e47d96f5653.jpg)

WP 5.9.3
Gutenberg plugin (latest)

**Comment by ajaydsouza** [comment]
@onetrev Please can you tell me what theme you're using for FSE?

**Comment by onetrev** [comment]
Sorry, should have mentioned that. I'm working with FrostWP. https://frostwp.com/

**Comment by ajaydsouza** [comment]
Thanks. I need to figure out how to do the placeholder text - this is only an issue on non-single posts, right? Because on the single you'd see the related posts.

**Comment by onetrev** [comment]
No this is on the "Single Post" template. And it's like this because the Template editor doesn't load dynamic content. It's all layout stuff. I'm very new to FSE, but that's how I believe it works. That's why things like "Site Title" or "Site Content" in the screenshot above show up for their blocks, because they are dynamic. The placeholder of Site Title is just to show you it there. :)

**Comment by ajaydsouza** [comment]
One more (and hopefully last) question and I'll experiment. Which are the blocks you've used for title/content? Or if it is easier, is there a way to copy all content and paste it here so I can import it into my test install

**Comment by onetrev** [comment]
No worries. Those are core blocks, were just included in template in the theme. Also, in there are other core blocks like "Post Featured Image" (which I added), "Post Date" and so on. Hope that helps!

**Comment by ajaydsouza** [comment]
Please can you check out this beta release: https://github.com/WebberZone/contextual-related-posts/releases/tag/v3.2.3-beta2

This should fix both issues. The block now displays a placeholder if you're not editing a post or if no posts are available.  Settings should also save.

**Comment by onetrev** [comment]
Tested and it's fixed. Works perfectly and looks good. Thank you many times over!

**Comment by ajaydsouza** [comment]
Thank you for confirming. I'll get this out.
