### ISSUE TITLE
Block needs placeholder text

### ISSUE THREAD

**Issue by onetrev** [WebberZone/contextual-related-posts#168]
When you insert the CRP block it does not display any placeholder text like other dynamic blocks. As such, you can't click on it anwhere. So it's a pain to have to open up the List View sidebar to find your way to the block to select it. :)

![needs-placeholder](https://user-images.githubusercontent.com/597601/166219444-5018943c-a6f2-4833-ae75-1ebd17769a93.jpg)

**Comment by ajaydsouza** [comment]
@onetrev I noticed this as well. I need to explore how to put that in place.

**Comment by onetrev** [comment]
Works perfectly now in v3.2.3 beta 2, thank you!
