### ISSUE TITLE
wp-graphql support

### ISSUE THREAD

**Issue by ShahriarKh** [WebberZone/contextual-related-posts#176]
It will be really cool if wp-graphql support is added, so we can query posts (or custom post types) with their related posts. Something like https://github.com/matepaiva/yarpp-wpgraphql that adds wp-graphql support for YARRP.

The plugin I mentioned above is a simple `add_action`.
https://github.com/matepaiva/yarpp-wpgraphql/blob/0ca36657a151a08b7ece1639a1d1e4030eb6b7db/yarpp-wpgraphql.php#L32
I tried to find the equivalent of `$yarrp->get_related()` in crp, but couldn't found it.

**Comment by ajaydsouza** [comment]
The equivalent should be [get_crp_posts](https://github.com/WebberZone/contextual-related-posts/blob/master/includes/main-query.php#L631). But note that it returns an array of WP_Post objects similar to what you'd get with WP_Query.

You might want to pass the fields parameter like you would with WP_Query to test this returning just IDs.

https://developer.wordpress.org/reference/classes/wp_query/#return-fields-parameter
