### ISSUE TITLE
Missing posts when using shortcode with ordering=date

### ISSUE THREAD

**Issue by Rafurus** [WebberZone/contextual-related-posts#180]
Hi, 

I'm using this shortcode 
`[crp limit=4 ordering=date post_types=post show_date=1]`
which should show 4 latest published posts. 
But I saw that specific posts are omitted even when I didn't turn off post from crp. 

What debug files do you need to check this?

**Comment by ajaydsouza** [comment]
The query produced will be helpful to analyse. You can also run this in phpMyAdmin or similar to see what posts this pulls out.

https://webberzone.com/support/knowledgebase/debugging-with-query-monitor/
