### ISSUE TITLE
"Related posts" structure displayed more than once per shown page/post

### ISSUE THREAD

**Issue by dMajoIT** [WebberZone/contextual-related-posts#184]
Used parameters:
- Display location priority 9999
- Insert after paragraph number -1
- Post/page IDs to exclude 12490,12494,12497
I use https://en-gb.wordpress.org/plugins/insert-pages/ to insert "private pages" into blog posts (mainly for contact forms)

** BUG-1
![re posts-bug1](https://github.com/WebberZone/contextual-related-posts/assets/71180767/d8bb5441-7b44-46db-90fd-fff770b57067)

At the end of the post, which have "inserted pages" into the body, your plugin displays the same "recent posts" structure more than once. Exatly the same number of inserted pages plus one (the plus one is normal because belongs to the shown blog post)

I've excluded the private pages post IDs, but it doesnt help.

It seems that you insert the placeholder everywhere and at the and you replace it with the related contents. Because of the inserted page the placeholder is found more than once and thus generate double/triple/ ... recent post displays one after the other at the end of the shown post.

You should use your param "Post/page IDs to exclude" as a filter and avoid to place the placeholder in these posts at all.

** BUG-2
![re posts-bug2](https://github.com/WebberZone/contextual-related-posts/assets/71180767/8ed345e3-004e-4b9c-ad39-10b9a268ff93)

Same issue with the plugin "The events calendar" https://en-gb.wordpress.org/plugins/the-events-calendar/
I have not investigated, but probably the page is made by inserting contents from more posts (the event, the venue, the organizer,..) and you place your placeholder on every single post, even if the finally displayed page/post is only one.

Regards

**Comment by dMajoIT** [comment]
Fortunately on "the events calendar" the bug don't displays the related posts one after the other but in two separate places of the page.

The plugin is very nice but unusable with this bug.

**Comment by ajaydsouza** [comment]
Thanks for this. I will investigate. It's likely because of the_content filter triggering and the checks I have to prevent it are clearly not enough as it's probably still in the loop.

One temporary option could be to disable the Automatically insert option in the settings page and either use it with the insert pages or similar plugin or if you can edit your theme files then do the manual install.

**Comment by ajaydsouza** [comment]
@dMajoIT 

I believe I have this fixed in this release candidate: https://github.com/WebberZone/contextual-related-posts/releases/tag/v3.3.4-RC1

**Comment by dMajoIT** [comment]
Sorry for late reply.
Yessssssss ..... issue solved. Nice work!

Once more congrats for this plugin as for me is the best in its class.

**Comment by ajaydsouza** [comment]
Thanks for the kind words. Could I please request you to leave a review when you have a moment?

https://wordpress.org/support/plugin/contextual-related-posts/reviews/
