### ISSUE TITLE
First image of post regex too greedy

### ISSUE THREAD

**Issue by Meltcap** [WebberZone/contextual-related-posts#2]
Hi,

First of all: thanks for writing the plugin!

I came across a bug in version 2.0.1 where the regex for the first post image is set too greedy. This results in the regex always returning the url of the last image of the post, instead of the first.

A working regex is (added 2 x '?'): `/<img.+?src=[\'"]([^\'"]+)[\'"].*?>/i`

The bug can be found in the file contextual-related-posts.php on line 1145.

**Comment by ajaydsouza** [comment]
Hi,

I've been trying the regex out and I get the same result irrespective of the two ?

In both cases it picks out the first image in the post content.

**Comment by Meltcap** [comment]
Hi,

That is odd because I got two different results. I'll try to reproduce it and send you an example later.

**Comment by ajaydsouza** [comment]
Thanks. That would be useful. Btw, I've been testing this on: https://regex101.com
