### ISSUE TITLE
Separate cache for https

### ISSUE THREAD

**Issue by ajaydsouza** [WebberZone/contextual-related-posts#43]
Using the same cache for https and http causes potential conflicts at times, especially when the SSL certificate is not validated.

Also, you don't want to show http links when a user is on an https page

**Comment by mikeyzm** [comment]
I think SQL query results should be cached instead of entire HTML.

**Comment by ajaydsouza** [comment]
The reason for caching the entire HTML is to speed it up completely. 

The SQL results will make my life a bit easier though, I must admit when dealing with different pages. My idea is to still use the HTML but use different keys based on settings

**Comment by mikeyzm** [comment]
There is negligible performance loss when generate HTML dynamically using PHP. Cache SQL results can make it become more flexible, more filters can be added.

Please consider my suggestion, and I'd like to help.

**Comment by ajaydsouza** [comment]
I'm happy to take any pull requests that would implement this.

The way I think about it is:

a) Add a separate meta field to store the cache. This should start with a `_` to keep it hidden from the Edit Post screen. Currently that cache doesn't use this name.
b) Add a separate option under cache settings to choose level of caching - advanced users can choose to only cache mySQL

Happy to hear suggestions to improve this.
