### ISSUE TITLE
Limit post title length (in characters) can't work well

### ISSUE THREAD

**Issue by hitrust** [WebberZone/contextual-related-posts#51]
If the original post title length shorter than the number that I set, It works well. But if longer than the number，then the post title cutted only output ... , in Chinese.

the numer I set is 36

The issue shows in the below attach file.

![2016-09-21_194358](https://cloud.githubusercontent.com/assets/3360631/18709672/de2d9a36-8033-11e6-8b6c-c4fda4e2efa8.png)
![2016-09-21_194103](https://cloud.githubusercontent.com/assets/3360631/18709671/ddf5903c-8033-11e6-825e-4a1013058429.png)

**Comment by ajaydsouza** [comment]
That's because there are no spaces in the post title. The option there is to set it to a much longer number.

**Comment by hitrust** [comment]
You say it's cuse there's no space for the title,but the option's tip says "Any title longer than the number of characters set above will be cut and appended with an ellipsis (…)", so the post title should be like this after cutted "欢乐颂.未删减.EP28.2016.HD720P.X264.AAC.Ma…" 
![2016-09-22_091315](https://cloud.githubusercontent.com/assets/3360631/18734224/d6551070-80a4-11e6-8bc7-1816d29104fd.png)

**Comment by ajaydsouza** [comment]
Yes, but it's also designed to not chop up single words when doing this. Hence the check for a space.

If you're typically using long post titles, then you should change the setting from 36 to a larger number.

An alternative, would be to simply write your own function filtering [crp_title](https://github.com/WebberZone/contextual-related-posts/blob/v2.2.3/includes/output-generator.php#L208) that removes the spaces. This is the function that [truncates the characters](https://github.com/WebberZone/contextual-related-posts/blob/v2.2.2/includes/tools.php#L60-L83).

As for the description above, I'll update it in the next version to make it clearer about the spaces.

**Comment by hitrust** [comment]
Thanks，I got it.
