### ISSUE TITLE
Add breadcrumb instead of just name for related articles

### ISSUE THREAD

**Issue by hbooo** [WebberZone/contextual-related-posts#64]
Hello, 
I use your plugin with docs instead of articles and it works well, the only problem is that I have a lot of docs that have the same name so i'm not able to differentiate them.

Is there a way to display the full breadcrumb of a doc instead of just its name?

Thanks in advance

**Comment by ajaydsouza** [comment]
You'll need to write a filter function for [`crp_title`](https://github.com/WebberZone/contextual-related-posts/blob/master/includes/output-generator.php#L208) to add whatever text / breadcrumb you need before the title.
