### ISSUE TITLE
Get IDs of related posts

### ISSUE THREAD

**Issue by jonasborneland** [WebberZone/contextual-related-posts#75]
I would love to just have the IDs of the post. Something like the simple:
```
if ( function_exists( 'echo_crp' ) ) { 	
	echo_crp(); 
}
```
That just returns the posts as IDs so you could fully customize the output

**Comment by ajaydsouza** [comment]
You can use [`get_crp_posts_id{}`](https://github.com/WebberZone/contextual-related-posts/blob/master/includes/main-query.php#L251)

**Comment by jonasborneland** [comment]
@ajaydsouza Ohh!! fantastic! Thanks for the quick response :)
