### ISSUE TITLE
Option to order by date

### ISSUE THREAD

**Issue by ajaydsouza** [WebberZone/contextual-related-posts#85]
Add a new option to order posts by date

**Comment by SteveP-UK** [comment]
Thanks for adding this Ajay! Happy to try beta. 👍☺️

**Comment by ajaydsouza** [comment]
@SteveP-UK this has now been implemented in the current beta in the repository

**Comment by SteveP-UK** [comment]
Cheers Ajay. I'm not very familiar with GitHub, can you point me to the link for the beta download?

**Comment by ajaydsouza** [comment]
It is at here - please test on a non-production install

https://github.com/WebberZone/contextual-related-posts/archive/master.zip

You'll need to make sure you replace the contextual-related-posts folder

The setting is a set of radio buttons under the Lists tab called "Order posts"
