### ISSUE TITLE
`get_crp_posts_id` got object but not array of post id

### ISSUE THREAD

**Issue by yaquawa** [WebberZone/contextual-related-posts#87]
I would expect the function `get_crp_posts_id` get an array of post id, but it got me an array of raw objects retrieved from database. 

To use the result of `get_crp_posts_id` in `WP_Query($args)`, I have to convert it to an array of ids.

```php
$ids = array_map(function ($obj) {
    return (int)$obj->ID;
}, get_crp_posts_id($args));

WP_Query(['post__in' => $ids]);
```

So why not just make it return an array of post ids in the first place?

**Comment by ajaydsouza** [comment]
The object was done intentionally - but let me see if I can add an extra option to export as an array. Idea was that I'd like to expand this to return a few more items in the future as I'm changing the related algorithm in a future version.

You can also use wp_list_pluck - see: https://gist.github.com/ajaydsouza/968b24a052e858bf8926#file-crp-plugin-api-examples-php

**Comment by ajaydsouza** [comment]
Latest version of CRP uses WP_Query and you can pass the same arguments.

You can use [get_crp_posts](https://github.com/WebberZone/contextual-related-posts/blob/master/includes/main-query.php#L672) instead and pass the [`fields` parameter](https://developer.wordpress.org/reference/classes/wp_query/#return-fields-parameter).

`get_crp_posts_id` will be eventually deprecated
