### ISSUE TITLE
Missing arguments for widget_title filter

### ISSUE THREAD

**Issue by florianbrinkmann** [WebberZone/contextual-related-posts#90]
Hi,

I am using the `widget_title` filter to modify the titles of category widgets. I need all three parameters of the core’s `apply_filters()` call (https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-includes/widgets/class-wp-widget-pages.php#L54) and get an error with the Contextual Related Posts plugin, because it uses `apply_filters( 'widget_title'`, but only with the title as a param. Could you add `$instance` and `$this->id_base` as additional parameters?

That would be great.

Thanks,
Florian

**Comment by ajaydsouza** [comment]
That is a good idea - I will add this into the next release.

**Comment by florianbrinkmann** [comment]
Great, thanks! :)
